"""Permanent regression tests generated from Design Partner Feedback.

AUTOMATICALLY GENERATED BY pilot/ingest_feedback.py.
DO NOT MANUALLY DELETE TEST CASES.
"""
import pytest
from phi_scanner.engine import ScanEngine
from phi_scanner.recognizers.aadhaar import find_aadhaar
from phi_scanner.recognizers.pan import find_pan
from phi_scanner.recognizers.gstin import find_gstin
from phi_scanner.recognizers.mobile import find_mobile



# Case 1: Currency amount falsely flagged as mobile number (Type: FP, Entity: IN_MOBILE)
def test_pilot_feedback_1_fp_in_mobile() -> None:
    sample_text = 'Rs. 5000000000'
    matches = find_mobile(sample_text)
    assert len(matches) == 0, f"False Positive reported by pilot partner: {sample_text!r}"


# Case 2: Spaced PAN was missed in old version (Type: FN, Entity: PAN)
def test_pilot_feedback_2_fn_pan() -> None:
    sample_text = 'ABC PD 5678 K'
    matches = find_pan(sample_text)
    assert len(matches) >= 1, f"False Negative reported by pilot partner: {sample_text!r}"


# Case 3: Order ID passed Verhoeff by random chance (Type: FP, Entity: AADHAAR)
def test_pilot_feedback_3_fp_aadhaar() -> None:
    sample_text = '123456789012'
    matches = [m for m in find_aadhaar(sample_text) if m.confidence.value == "HIGH"]
    assert len(matches) == 0, f"False Positive reported by pilot partner: {sample_text!r}"

