"""Tests for the Aadhaar recognizer and Verhoeff algorithm.

Precision target (rules.md / prd.md): >95% on checksum-validated identifiers.
Results recorded here after each run for memory.md.
"""
import pytest

from phi_scanner.recognizers.aadhaar import (
    Confidence,
    find_aadhaar,
    verhoeff_check_digit,
    verhoeff_validate,
)
from tests.corpus.aadhaar_corpus import (
    HARD_NEGATIVES,
    TRUE_POSITIVES,
    TRUE_POSITIVE_VARIANTS,
)


# ---------------------------------------------------------------------------
# Verhoeff primitive tests
# ---------------------------------------------------------------------------

class TestVerhoeff:
    def test_valid_number_passes(self) -> None:
        # All TRUE_POSITIVES were generated by verhoeff_check_digit
        for number in TRUE_POSITIVES:
            assert verhoeff_validate(number), f"Expected {number} to pass Verhoeff"

    def test_check_digit_round_trip(self) -> None:
        prefix = "23456789012"
        digit = verhoeff_check_digit(prefix)
        assert verhoeff_validate(prefix + digit)

    def test_off_by_one_fails(self) -> None:
        number = TRUE_POSITIVES[0]
        last = str((int(number[-1]) + 1) % 10)
        corrupted = number[:-1] + last
        assert not verhoeff_validate(corrupted)


# ---------------------------------------------------------------------------
# Recognizer — true positives
# ---------------------------------------------------------------------------

class TestAadhaarTruePositives:
    @pytest.mark.parametrize("number", TRUE_POSITIVES)
    def test_bare_number_is_detected(self, number: str) -> None:
        matches = find_aadhaar(number)
        assert len(matches) == 1
        assert matches[0].confidence == Confidence.HIGH

    @pytest.mark.parametrize("text", TRUE_POSITIVE_VARIANTS)
    def test_variant_formats_detected(self, text: str) -> None:
        matches = find_aadhaar(text)
        assert len(matches) >= 1, f"No match found in: {text!r}"
        assert any(m.confidence == Confidence.HIGH for m in matches)

    def test_masked_value_hides_first_eight(self) -> None:
        number = TRUE_POSITIVES[0]
        m = find_aadhaar(number)[0]
        assert m.masked_value.startswith("XXXX XXXX")
        assert m.masked_value.endswith(number[-4:])


# ---------------------------------------------------------------------------
# Recognizer — hard negatives
# ---------------------------------------------------------------------------

class TestAadhaarHardNegatives:
    @pytest.mark.parametrize("case", HARD_NEGATIVES)
    def test_hard_negative_not_high_confidence(self, case: dict) -> None:
        matches = find_aadhaar(case["value"])
        high_matches = [m for m in matches if m.confidence == Confidence.HIGH]
        assert len(high_matches) == 0, (
            f"Expected no HIGH match for reason={case['reason']!r}, "
            f"value={case['value']!r}, got {matches}"
        )

    def test_first_digit_zero_not_detected(self) -> None:
        # Starts with 0 — explicitly excluded from pattern
        assert find_aadhaar("012345678901") == []

    def test_first_digit_one_not_detected(self) -> None:
        assert find_aadhaar("112345678901") == []

    def test_embedded_in_longer_string_not_detected(self) -> None:
        # 12-digit valid Aadhaar embedded inside a 15-digit string
        valid = TRUE_POSITIVES[0]
        assert find_aadhaar(f"123{valid}456") == []


# ---------------------------------------------------------------------------
# Precision / recall record (update in memory.md after each run)
# ---------------------------------------------------------------------------

class TestPrecisionRecall:
    """Automated precision/recall measurement against the synthetic corpus."""

    def test_precision_on_bare_true_positives(self) -> None:
        tp = sum(1 for n in TRUE_POSITIVES if find_aadhaar(n))
        precision = tp / len(TRUE_POSITIVES)
        # Record: precision={precision:.2%} on {len(TRUE_POSITIVES)} true positives
        assert precision == 1.0, f"Precision dropped to {precision:.2%}"

    def test_false_positive_rate_on_hard_negatives(self) -> None:
        fp = sum(
            1 for c in HARD_NEGATIVES
            if any(m.confidence == Confidence.HIGH for m in find_aadhaar(c["value"]))
        )
        fpr = fp / len(HARD_NEGATIVES)
        # Record: false positive rate (HIGH) = {fpr:.2%} on hard negatives
        assert fpr == 0.0, f"False positive rate is {fpr:.2%}"
