"""Ingest design partner feedback CSV into permanent regression test cases.

Per phases.md §39:
"Track every false positive and false negative against the test corpus —
 if a partner finds one, it becomes a permanent regression test, not a one-off fix."

Usage:
  python pilot/ingest_feedback.py pilot/FEEDBACK_TEMPLATE.csv
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

REGRESSION_TEST_FILE = Path(__file__).parent.parent / "tests" / "test_pilot_regressions.py"

_TEMPLATE = """\"\"\"Permanent regression tests generated from Design Partner Feedback.

AUTOMATICALLY GENERATED BY pilot/ingest_feedback.py.
DO NOT MANUALLY DELETE TEST CASES.
\"\"\"
import pytest
from phi_scanner.engine import ScanEngine
from phi_scanner.recognizers.aadhaar import find_aadhaar
from phi_scanner.recognizers.pan import find_pan
from phi_scanner.recognizers.gstin import find_gstin
from phi_scanner.recognizers.mobile import find_mobile


"""


def generate_regression_code(rows: list[dict[str, str]]) -> str:
    lines = [_TEMPLATE]

    for idx, r in enumerate(rows, start=1):
        fb_type = r.get("feedback_type", "").strip().upper()
        entity = r.get("entity_type", "").strip().upper()
        sample = r.get("raw_sample_value", "").strip()
        column = r.get("context_column", "").strip()
        notes = r.get("notes", "").strip()

        if not sample:
            continue

        func_name = f"test_pilot_feedback_{idx}_{fb_type.lower()}_{entity.lower()}"

        lines.append(f"# Case {idx}: {notes} (Type: {fb_type}, Entity: {entity})")

        if fb_type == "FP":
            # False Positive: scanner should NOT find this entity type with HIGH confidence
            lines.append(f"def {func_name}() -> None:")
            lines.append(f'    sample_text = {repr(sample)}')
            if entity == "AADHAAR":
                lines.append(f'    matches = [m for m in find_aadhaar(sample_text) if m.confidence.value == "HIGH"]')
            elif entity == "PAN":
                lines.append(f'    matches = [m for m in find_pan(sample_text) if m.confidence.value == "HIGH"]')
            elif entity == "GSTIN":
                lines.append(f'    matches = [m for m in find_gstin(sample_text) if m.confidence.value == "HIGH"]')
            elif entity == "IN_MOBILE":
                lines.append(f'    matches = find_mobile(sample_text)')
            else:
                lines.append(f'    matches = []')
            lines.append(f'    assert len(matches) == 0, f"False Positive reported by pilot partner: {{sample_text!r}}"')

        elif fb_type == "FN":
            # False Negative: scanner MUST detect this entity
            lines.append(f"def {func_name}() -> None:")
            lines.append(f'    sample_text = {repr(sample)}')
            if entity == "AADHAAR":
                lines.append(f'    matches = find_aadhaar(sample_text)')
            elif entity == "PAN":
                lines.append(f'    matches = find_pan(sample_text)')
            elif entity == "GSTIN":
                lines.append(f'    matches = find_gstin(sample_text)')
            elif entity == "IN_MOBILE":
                lines.append(f'    matches = find_mobile(sample_text)')
            else:
                lines.append(f'    matches = []')
            lines.append(f'    assert len(matches) >= 1, f"False Negative reported by pilot partner: {{sample_text!r}}"')

        lines.append("\n")

    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python pilot/ingest_feedback.py <path_to_feedback.csv>")
        sys.exit(1)

    feedback_csv = Path(sys.argv[1])
    if not feedback_csv.exists():
        print(f"Error: file not found {feedback_csv}")
        sys.exit(1)

    with open(feedback_csv, encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)

    code = generate_regression_code(rows)
    with open(REGRESSION_TEST_FILE, "w", encoding="utf-8") as fh:
        fh.write(code)

    print(f"Ingested {len(rows)} feedback cases into: {REGRESSION_TEST_FILE}")


if __name__ == "__main__":
    main()
