"""Synthetic GSTIN test corpus.

Known valid GSTIN used for algorithm verification:
  27AAPFU0939F1ZV — Maharashtra, verified against GST portal checksum.

True positives are generated by: building a valid 14-char prefix, then
appending the correct check digit from _gstin_check_digit.
"""
from phi_scanner.recognizers.gstin import _gstin_check_digit

_CHARS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"


def _make(prefix14: str) -> str:
    return prefix14 + _gstin_check_digit(prefix14)


# ---------------------------------------------------------------------------
# True positives
# ---------------------------------------------------------------------------
TRUE_POSITIVES: list[str] = [
    "27AAPFU0939F1ZV",           # real-format example (publicly documented)
    _make("29ABCPD1234E1Z"),     # Karnataka, individual
    _make("07XYZCA5678F2Z"),     # Delhi, company
    _make("33DEFHG2345K1Z"),     # Tamil Nadu, HUF
    _make("19MNOFS6789L1Z"),     # West Bengal, firm
    _make("06PQRAT1111M3Z"),     # Haryana, AOP
]

TRUE_POSITIVE_VARIANTS: list[str] = [
    f"GSTIN: {TRUE_POSITIVES[0]}",
    f"gst no {TRUE_POSITIVES[1].lower()}",   # lowercase
    f"  {TRUE_POSITIVES[2]}  ",              # whitespace padded
]

# ---------------------------------------------------------------------------
# Hard negatives
# ---------------------------------------------------------------------------
HARD_NEGATIVES: list[dict] = [
    # Valid structure but wrong check digit
    {
        "value": "27AAPFU0939F1ZW",   # last char should be V
        "reason": "wrong_check_digit",
    },
    # Invalid state code 00
    {
        "value": _make("00ABCPD1234E1Z"),
        "reason": "state_code_00",
    },
    # Invalid state code 39
    {
        "value": _make("39ABCPD1234E1Z"),
        "reason": "state_code_39",
    },
    # 14 chars — too short
    {
        "value": "27AAPFU0939F1Z",
        "reason": "too_short_14",
    },
    # 16 chars — too long
    {
        "value": "27AAPFU0939F1ZVX",
        "reason": "too_long_16",
    },
    # Position 14 not 'Z' — structurally invalid
    {
        "value": "27AAPFU0939F1XV",
        "reason": "no_Z_at_pos_14",
    },
]
